CREATE TABLE [dbo].[wordsEn](
	[TheWord] [varchar](50) NOT NULL,
	[WordID] [int] IDENTITY(1,1) NOT NULL,
	CONSTRAINT [PK_wordsEn] PRIMARY KEY CLUSTERED 
	(
		[TheWord] ASC
	)
	WITH 
	(
		PAD_INDEX = OFF
		, STATISTICS_NORECOMPUTE = OFF
		, IGNORE_DUP_KEY = OFF
		, ALLOW_ROW_LOCKS = ON
		, ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_WORDS_WORDID] ON [dbo].[wordsEn]
(
	[WordID] ASC
)
INCLUDE 
( 	
	[TheWord]
) 
WITH 
(
	PAD_INDEX = OFF
	, STATISTICS_NORECOMPUTE = OFF
	, SORT_IN_TEMPDB = OFF
	, DROP_EXISTING = OFF
	, ONLINE = OFF
	, ALLOW_ROW_LOCKS = ON
	, ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]
GO


